"use client";

import { useState, useTransition } from "react";
import {
  generateToolsContent,
  ApiError,
} from "@/lib/content-writer/api";
import type { GeneratedContentSet } from "@/lib/content-writer/types";

/**
 * Content Creator addition on CWV2: remind operators how tools work, and run
 * POST /api/projects/{id}/generate/tools (CWV2 GenerateController) when the pillar
 * Tools section exists. Human names alone are not enough for that endpoint — they
 * must appear in the pillar Tools section (or regenerate pillar with those tools).
 */
export default function HumanToolsHint({
  projectId,
  canRunTools,
  onGenerated,
}: {
  projectId: string;
  canRunTools: boolean;
  onGenerated: (result: GeneratedContentSet) => void;
}) {
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [hint, setHint] = useState("");

  function run() {
    setError(null);
    startTransition(async () => {
      try {
        const next = await generateToolsContent(projectId);
        onGenerated(next);
      } catch (e) {
        const msg =
          e instanceof ApiError
            ? e.message
            : "Tool generate failed. Ensure the pillar body has a Tools section.";
        setError(msg);
      }
    });
  }

  return (
    <section className="rounded-xl border border-border bg-surface p-6 shadow-sm">
      <h2 className="text-lg font-semibold text-foreground">AI Tools (CWV2)</h2>
      <p className="mt-1 text-sm text-muted">
        Tool pages are generated by Content Writer v2 from the pillar&apos;s{" "}
        <strong className="font-medium text-foreground">Tools</strong> section
        (<code className="text-xs">POST …/generate/tools</code>). List tool names you want
        in Desired Headings or ensure the pillar plan includes them, write the pillar body,
        then generate tools here.
      </p>

      <label className="mt-4 block space-y-1.5">
        <span className="text-sm font-medium text-foreground">
          Names to include in the pillar (optional reminder)
        </span>
        <textarea
          value={hint}
          onChange={(e) => setHint(e.target.value)}
          rows={2}
          placeholder="One per line — copy into Desired Headings before Generate plan"
          className="w-full rounded-md border border-border bg-white px-3 py-2 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/20"
        />
      </label>

      {hint.trim() ? (
        <p className="mt-2 text-xs text-muted">
          Suggested Desired Headings value:{" "}
          <span className="font-mono text-foreground">
            {hint
              .split(/[\n,]/)
              .map((s) => s.trim())
              .filter(Boolean)
              .join(", ")}
          </span>
        </p>
      ) : null}

      <button
        type="button"
        disabled={pending || !canRunTools}
        onClick={run}
        className="mt-4 rounded-md bg-brand px-4 py-2 text-sm font-semibold text-white hover:bg-brand/90 disabled:opacity-50"
      >
        {pending ? "Generating tools…" : "Generate tools (CWV2)"}
      </button>
      {!canRunTools ? (
        <p className="mt-2 text-xs text-muted">
          Write the pillar body first (step 5.2), then run tools.
        </p>
      ) : null}
      {error ? <p className="mt-2 text-sm text-red-600">{error}</p> : null}
    </section>
  );
}
